### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Davy49** [tiancihe/bookmark-manager#2]
Hi,
While this is an interesting add-on that tries to replicate the chrome bookmark manager, it still lacks some of the features that the chrome version has. For instance, the bookmark's can't be sorted like in chrome, plus this add-on seems to lack virtually no settings at all. This is just some 'constructive' criticism.

**Comment by tiancihe** [comment]
@Davy49 there are some features i don't implement because i don't think they are useful (for me personally), e.g. i don't usually sort my bookmarks, i just put them into a folder, and use search to find them. if you think a feature is useful, you can open an issue to address that feature exclusively, i will try to implement it when i get some spare time, and btw, may i ask what does "lack virtually no settings" mean, i don't quite understand that phrase.
